language: node_js
node_js:
- '16'
script:
- npm install
- npm test
env:
  global:
    secure: HzmIFOpJ5NTDoBiZQha7D00KcCG1F/AIbzR6TH9k/uUpezRv7lt4B8aszFdjtgl+c5MNZYrY3oKPs3RyAKmL7uvPY7fWjAvLjCjVdYVtv0g/l0uCfnl49Gt41IvrsR0lI766Ug+0RGVV5czAdx4H+Zb+Un2sRhbxtqtJW935JK65loLDtUJRI2xSkGOuo7Iy1U+urgSSF1PW5D2h+kHX/oBt7R/4De8HuMsWfa+897kVIKx3kDeMqGPt0rW7UaJTWldpd/7AxWUDVFwTxv8Yxbvmo9T1enSksrlOlGmGhqzTJfpg6CTvNhKVQmDTKHqwLfFXwBXgC8m8aOqzjDEzOxw7fh023ZKkyrx+T2uuCZApNrVC9N98niw3npoXOsF+PdIFp1mAuucz/ah9deEfYGbNjSUwF+/+Aadd2UO/AN58gymApEWOoeXETBe3HZMYdNo8fTv4LBA+Kdd6tKh5erGNz9gbXc5d5JHV8Ct7eXEyDFMkcz2Ezcn7Zhu+D8akCBAztn7TSIWvSU8/E2FSkrBs4hyEhzkqVGoTpNxOzzANTG2FC/q2fTCy4K+I6Ymm6iIym3Dcu10Y4xxkBzH+dNU+WVBYlFzXuG+4EMt1/G9XRTBE8FbiuvcU6QhAxH7epoTm0umxbUJTmC52Mpf0U3PjcymVnn3Z7AlxeBLBkKY=
